version: "3.3"

services:

  db: 
      image: mysql:latest
      container_name: mysql_db
      ports:
        - "3306:3306"
      networks:
        - custom  
      environment:
        MYSQL_ROOT_PASSWORD: root_secret123
        MYSQL_DATABASE: Music_Database
        MYSQL_USER: user1
        MYSQL_PASSWORD: dbsecret123
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        - db-data:/var/lib/mysql

  admin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpadmin
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      ports:
        - "8080:80"
      networks:
        - custom 
      depends_on: 
        - "db"


volumes:
  db-data:

networks:
  custom:
    driver: bridge